// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRWmzQonZvRSzLQZrzH9BWMyvdK0pdqLo',
    appId: '1:544925751012:web:00993a8db08e97d55d7ef1',
    messagingSenderId: '544925751012',
    projectId: 'mnote-8db27',
    authDomain: 'mnote-8db27.firebaseapp.com',
    storageBucket: 'mnote-8db27.firebasestorage.app',
    measurementId: 'G-017JNXXR6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBirK1iCOB35--XnAIp4n7dKGqNe9PNzl8',
    appId: '1:544925751012:android:c6273ada0310dce35d7ef1',
    messagingSenderId: '544925751012',
    projectId: 'mnote-8db27',
    storageBucket: 'mnote-8db27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2idbbLvGqphJTEiStC4dHiJSNjIo4JXY',
    appId: '1:544925751012:ios:8eecac9242d982f25d7ef1',
    messagingSenderId: '544925751012',
    projectId: 'mnote-8db27',
    storageBucket: 'mnote-8db27.firebasestorage.app',
    iosBundleId: 'com.petchauisui.mnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2idbbLvGqphJTEiStC4dHiJSNjIo4JXY',
    appId: '1:544925751012:ios:8eecac9242d982f25d7ef1',
    messagingSenderId: '544925751012',
    projectId: 'mnote-8db27',
    storageBucket: 'mnote-8db27.firebasestorage.app',
    iosBundleId: 'com.petchauisui.mnote',
  );
}
